config_data:
  task: pictureDescription
  transcript_version: google
config_audio_features:
  feature_groups:
  - opensmile_features
  - pause_features
  - phoneme_features
  feature_version: reduced  # reduced set of features - without too strong correlations
config_linguistic_features:
  feature_groups:
  - csunghye_features
  - literature_features
  #- LIWC_features
  feature_version: reduced  # reduced set of features - without too strong correlations
config_model:
  model_name: LogisticRegression
  target_variable: composite_language
  classification_labels: negative_outliers
debug: false
model: Classification
data_transformers:
- Linguistic Features
- Audio Features
- Demographic Features
data_preprocessors:
- Outlier Removal and Imputation
- Feature Standardizer
