name: dementia
channels:
  - pytorch
  - anaconda
  - ets
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - accelerate=0.33.0=pyhd8ed1ab_0
  - aiohttp=3.8.6=py39h17cfd9d_1
  - aiohttp-retry=2.8.3=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amqp=5.2.0=pyhd8ed1ab_1
  - annotated-types=0.6.0=py39hca03da5_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.7.1=h463b476_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h0f82c59_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - asyncssh=2.17.0=pyhd8ed1ab_0
  - atpublic=5.0=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - audioread=3.0.1=py39h2804cbe_1
  - aws-c-auth=0.7.5=he6edc6d_0
  - aws-c-cal=0.6.7=ha251d5a_0
  - aws-c-common=0.9.4=h93a5062_0
  - aws-c-compression=0.2.17=ha251d5a_4
  - aws-c-event-stream=0.3.2=hd73d0d5_4
  - aws-c-http=0.7.13=hb3e5a72_7
  - aws-c-io=0.13.35=h0f79f92_4
  - aws-c-mqtt=0.9.8=he2964ae_0
  - aws-c-s3=0.3.20=h8d12f51_1
  - aws-c-sdkutils=0.1.12=ha251d5a_3
  - aws-checksums=0.1.17=ha251d5a_3
  - aws-crt-cpp=0.24.4=h5f3d163_2
  - aws-sdk-cpp=1.11.182=hba14a0b_2
  - babel=2.13.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - backports.zoneinfo=0.2.1=py39h2804cbe_8
  - basemap=1.4.1=np126py39h95066b0_0
  - basemap-data=1.3.2=pyhd8ed1ab_3
  - beautifulsoup4=4.12.2=pyha770c72_0
  - billiard=4.2.0=py39h06df861_1
  - binaryornot=0.4.4=py_1
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py39hb198ff7_1
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.21.0=h93a5062_0
  - ca-certificates=2025.9.9=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hd1e100b_0
  - celery=5.4.0=pyhd8ed1ab_1
  - certifi=2025.8.3=py39hca03da5_0
  - cffi=1.16.0=py39he153c15_0
  - chardet=5.2.0=py39h2804cbe_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - click-repl=0.2.0=pyhd3eb1b0_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - configobj=5.0.6=py39hca03da5_1
  - contourpy=1.1.1=py39hbd775c9_1
  - cookiecutter=2.4.0=pyhca7485f_0
  - cryptography=43.0.0=py39hd4332d6_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.19.1=py39hca03da5_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.0=py39hb198ff7_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dictdiffer=0.9.0=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - diskcache=5.6.3=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_0
  - dulwich=0.22.1=py39h9c3e640_1
  - dvc=3.55.2=pyhd8ed1ab_0
  - dvc-data=3.16.5=pyhd8ed1ab_0
  - dvc-http=2.32.0=pyhd8ed1ab_0
  - dvc-objects=5.1.0=pyhd8ed1ab_1
  - dvc-render=1.0.2=pyhd8ed1ab_0
  - dvc-studio-client=0.21.0=pyhd8ed1ab_0
  - dvc-task=0.4.0=pyhd8ed1ab_0
  - emoji=2.8.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - evaluate=0.4.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - factor_analyzer=0.5.1=py_0
  - ffmpeg=6.1.1=gpl_h4d3b11e_100
  - ffmpeg-python=0.2.0=py_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - flatten-dict=0.4.2=pyhd8ed1ab_1
  - flufl.lock=8.1.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.43.1=py39h17cfd9d_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.4.0=py39h0f82c59_1
  - fsspec=2024.3.1=py39hca03da5_0
  - funcy=2.0=pyhd8ed1ab_0
  - future=0.18.3=py39hca03da5_0
  - gdk-pixbuf=2.42.10=h15fa40c_4
  - geos=3.12.1=h965bd2d_0
  - gettext=0.21.1=h0186832_0
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h80987f9_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py39hca03da5_0
  - glib=2.78.3=h9e231a4_0
  - glib-tools=2.78.3=h9e231a4_0
  - glog=0.6.0=h6da1cb0_0
  - gmp=6.3.0=h965bd2d_0
  - gmpy2=2.1.2=py39h0b4f9c6_1
  - gnutls=3.7.9=hd26332c_0
  - grandalf=0.7=pyhd8ed1ab_0
  - graphite2=1.3.13=h9f76cd9_1001
  - graphviz=2.50.0=hf331ead_1
  - gto=1.7.1=pyhd8ed1ab_1
  - gts=0.7.6=hde733a8_3
  - h11=0.14.0=py39hca03da5_0
  - harfbuzz=8.3.0=h8f0ba13_0
  - httpcore=1.0.2=py39hca03da5_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - hypothesis=6.88.1=pyha770c72_0
  - icu=73.2=hc8870d7_0
  - idna=3.4=pyhd8ed1ab_0
  - imbalanced-learn=0.12.0=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.1.0=pyhd8ed1ab_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.26.0=pyh3cd1d5f_0
  - ipython=8.17.2=pyh31c8845_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - iterative-telemetry=0.0.8=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=py39hca03da5_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py39h2804cbe_3
  - jsonschema=4.19.2=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.2=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.5.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py39h2804cbe_0
  - jupyter_events=0.8.0=pyhd8ed1ab_0
  - jupyter_server=2.9.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.3.4=py39hca03da5_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.27.3=py39hca03da5_0
  - kiwisolver=1.4.5=py39hbd775c9_1
  - kombu=5.4.0=py39h2804cbe_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a8c8d9_1003
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.15=hf2736f0_3
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libarrow=13.0.0=h87fad27_13_cpu
  - libass=0.17.1=hf7da4fe_1
  - libblas=3.9.0=19_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=19_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h642e427_1
  - libevent=2.1.12=h2757513_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libflac=1.4.3=hb765f3a_0
  - libgd=2.3.3=hfdf3952_9
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libgit2=1.7.2=h9878266_0
  - libglib=2.78.3=hb438215_0
  - libgoogle-cloud=2.12.0=h5a37b55_3
  - libgrpc=1.58.2=h19be7b0_0
  - libhwloc=2.9.3=default_h4394839_1009
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=19_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.4=h27ca646_1
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h76d750c_0
  - libpq=12.15=h02f6b3c_1
  - libprotobuf=4.24.3=hf590ac1_1
  - libre2-11=2023.06.02=h1753957_0
  - librosa=0.10.1=pyhd8ed1ab_0
  - librsvg=2.56.3=h55a2576_1
  - libsndfile=1.2.2=h9739721_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=ha8a6c65_2
  - libtool=2.4.6=h313beb8_1009
  - libunistring=0.9.10=h3422bc3_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libuv=1.46.0=hb547adb_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.13.1=hb765f3a_0
  - libwebp=1.3.2=hf30222e_1
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxgboost=2.0.3=cpu_h40478aa_1
  - libxml2=2.12.3=h0d0cfa8_0
  - libzlib=1.2.13=h53f4e23_5
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - littleutils=0.2.2=py_0
  - llvm-openmp=19.1.6=hdb05f8b_0
  - llvmlite=0.42.0=py39h047a24b_1
  - lz4-c=1.9.4=hb7217d7_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39h0f82c59_1
  - matplotlib=3.8.1=py39hdf13c20_0
  - matplotlib-base=3.8.1=py39h1a09f3e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h9546428_0
  - mpg123=1.32.3=h13dd4ca_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.6=py39hbd775c9_0
  - multidict=6.0.4=py39h02fc5c5_1
  - multiprocess=0.70.15=py39h0f82c59_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mutagen=1.47.0=pyhd8ed1ab_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.10.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.5=hb89a1cb_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.9.1=h40ed0f5_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nltk=3.8.1=py39hca03da5_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.3.2=py39hca03da5_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=h313beb8_0
  - nss=3.100=hc6e9f88_0
  - numba=0.59.1=py39h313beb8_0
  - numpy=1.26.4=py39h7aa2656_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openh264=2.4.0=h965bd2d_0
  - openjpeg=2.5.0=h4c1507b_3
  - openpyxl=3.1.2=py39h0f82c59_0
  - openssl=3.3.1=hfb2fe0b_2
  - orc=1.9.0=hcd02cb2_3
  - orjson=3.9.15=py39hc9796cf_0
  - outdated=0.2.2=pyhd8ed1ab_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.2=py39hf8cecc8_0
  - pandas-flavor=0.6.0=pyhd8ed1ab_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=hcf40dda_2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathlib2=2.3.6=py39hca03da5_2
  - pathspec=0.10.3=py39hca03da5_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.42=hb066dcc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pingouin=0.5.4=pyhd8ed1ab_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h13dd4ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - plotly=5.18.0=pyhd8ed1ab_0
  - pluggy=1.5.0=py39hca03da5_0
  - pooch=1.8.0=pyhd8ed1ab_0
  - poppler=23.12.0=hcdd998b_0
  - poppler-data=0.4.11=hca03da5_1
  - proj=9.4.0=h52fb9d0_1
  - prometheus_client=0.18.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=4.24.3=py39h6b23cf8_1
  - psutil=5.9.5=py39h0f82c59_1
  - psycopg2=2.9.3=py39h80987f9_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=2.0.3=cpu_pyheee7c3a_1
  - pyarrow=13.0.0=py39h5c469ea_13_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyctcdecode=0.5.0=pyhd8ed1ab_0
  - pydot=1.4.1=py39hca03da5_0
  - pygit2=1.14.1=py39h17cfd9d_1
  - pygments=2.16.1=pyhd8ed1ab_0
  - pygtrie=2.5.0=pyhd8ed1ab_0
  - pyobjc-core=10.0=py39h4d1a642_0
  - pyobjc-framework-cocoa=10.0=py39h4d1a642_1
  - pyopenssl=24.2.1=py39hca03da5_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py39h1c728a2_7
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - pytest=8.3.4=py39hca03da5_0
  - python=3.9.18=hfa1ae8a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_1
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python-gssapi=1.8.3=py39h80987f9_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_2
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py39h0f82c59_0
  - python_abi=3.9=4_cp39
  - pytorch=2.1.2=py3.9_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py39h0f82c59_1
  - pyzmq=25.1.1=py39he0a3c8b_2
  - re2=2023.06.02=h6135d0a_0
  - readline=8.2=h92ec313_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - regex=2023.10.3=py39h0f82c59_0
  - requests=2.31.0=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.6.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py39h8fec3ad_0
  - ruamel.yaml=0.17.21=py39h1a28f6b_0
  - ruamel.yaml.clib=0.2.6=py39h1a28f6b_1
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.4.2=py39h482802a_0
  - scikit-learn=1.6.1=py39h313beb8_0
  - scipy=1.11.3=py39h89ddb1b_1
  - scmrepo=3.3.7=pyhd8ed1ab_0
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - semver=3.0.2=py39hca03da5_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shap=0.42.1=py39h46d7db6_0
  - shellingham=1.5.0=py39hca03da5_0
  - shortuuid=1.0.13=pyhd8ed1ab_0
  - shtab=1.7.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - slicer=0.0.7=pyhd3eb1b0_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - soxr=0.1.3=h5008568_3
  - soxr-python=0.3.7=py39h373d45f_0
  - sqlite=3.46.0=h5838104_0
  - sqltrie=0.11.1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stanza=1.6.1=pyhd8ed1ab_0
  - statsmodels=0.14.0=py39h373d45f_2
  - svt-av1=1.8.0=h463b476_0
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.11.0=h2ffa867_1
  - tenacity=8.2.3=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - text-unidecode=1.3=pyhd8ed1ab_1
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=hb31c410_0
  - tokenizers=0.19.1=py39h92154f2_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.1=py39hca03da5_0
  - torchaudio=2.1.2=py39_cpu
  - torchmetrics=1.2.0=pyhd8ed1ab_0
  - torchvision=0.16.2=py39_cpu
  - tornado=6.3.3=py39h0f82c59_1
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typer=0.9.0=py39hca03da5_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.1.0=py39h0f82c59_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - vine=5.1.0=pyhd8ed1ab_0
  - voluptuous=0.15.2=pyhd8ed1ab_1
  - wcwidth=0.2.9=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xxhash=0.8.2=hb547adb_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.2=py39h17cfd9d_1
  - zc.lockfile=2.0=pyhd3eb1b0_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - anyio==3.7.1
      - audeer==2.1.1
      - audformat==1.3.0
      - audinterface==1.2.2
      - audiofile==1.4.0
      - audmath==1.4.1
      - audobject==0.7.11
      - audresample==1.3.3
      - bertviz==1.4.0
      - bibtexparser==2.0.0b7
      - boto3==1.28.77
      - botocore==1.31.77
      - cachetools==5.3.2
      - clldutils==3.22.2
      - colorlog==6.8.2
      - csvw==3.3.0
      - deepmultilingualpunctuation==1.0.1
      - distro==1.8.0
      - dlinfo==1.2.1
      - einops==0.8.0
      - google-api-core==2.12.0
      - google-auth==2.23.4
      - google-cloud-core==2.3.3
      - google-cloud-speech==2.22.0
      - google-cloud-storage==2.13.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.61.0
      - grpcio==1.59.2
      - grpcio-status==1.59.2
      - hf-xet==1.1.8
      - httpx==0.25.2
      - huggingface-hub==0.34.4
      - imageio==2.31.6
      - ipywidgets==8.1.7
      - iso-639==0.4.5
      - iso3166==2.1.1
      - isodate==0.6.1
      - jiwer==3.0.3
      - jupyterlab-widgets==3.0.15
      - language-tags==1.2.0
      - lightgbm==4.5.0
      - lime==0.2.0.1
      - lxml==5.3.0
      - markdown==3.6
      - matlabengine==24.2
      - openai==1.12.0
      - opencv-python-headless==4.10.0.84
      - opensmile==2.5.0
      - oyaml==1.0
      - peft==0.17.0
      - phonemizer==3.3.0
      - pillow==10.0.1
      - proto-plus==1.22.3
      - pyaml==25.7.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pydub==0.25.1
      - pylatexenc==2.10
      - pympler==1.0.1
      - pypng==0.20220715.0
      - qrcode==7.4.2
      - rapidfuzz==3.5.2
      - rdflib==7.0.0
      - reportlab==4.2.2
      - rfc3986==1.5.0
      - rsa==4.9
      - s3transfer==0.7.0
      - scikit-image==0.22.0
      - scikit-optimize==0.10.2
      - segments==2.2.1
      - sentencepiece==0.1.99
      - striprtf==0.0.26
      - tabpfn==2.0.1
      - tifffile==2023.9.26
      - tqdm==4.67.1
      - transformers==4.17.0
      - uritemplate==4.1.1
      - urllib3==1.26.18
      - webrtcvad==2.0.10
      - widgetsnbextension==4.0.14
prefix: /Users/jheitz/miniconda3/envs/dementia
